// Second, harder test set: casual wording, typos, exact details, and close-but-unanswerable questions.
// Ground truth checked with grep against docs/project-atlas. [] = the docs do not answer it.
export const queries2 = [
  { id: 'A1', set: 'new', q: 'how do you say the product name out loud', rel: ['brand-and-ui'] },
  { id: 'A2', set: 'new', q: 'what kinds of files can i drag in', rel: ['document-operations', 'canvas-ui'] },
  { id: 'A3', set: 'new', q: 'at what zoom do cards start showing the whole page', rel: ['canvas-ui'] },
  { id: 'A4', set: 'new', q: 'how long can someone keep an edit claim on a page', rel: ['architecture', 'sdk-and-webmcp'] },
  { id: 'A5', set: 'new', q: 'which port does the backend listen on while developing', rel: ['operations', 'mcp-and-api', 'sdk-and-webmcp'] },
  { id: 'A6', set: 'new', q: 'how many automated checks does the project have', rel: ['testing', 'system-map', 'history', 'plan-status', 'README'] },
  { id: 'A7', set: 'new', q: 'what typeface is used for code', rel: ['brand-and-ui', 'system-map'] },
  { id: 'A8', set: 'new', q: 'can i save the research diagram to a file', rel: ['assistant-and-research'] },
  { id: 'A9', set: 'new', q: 'what does the app do when the decision service is rate limiting us', rel: ['errors', 'sdk-and-webmcp', 'reflex-internals', 'chat-internals'] },
  { id: 'A10', set: 'new', q: 'can a web page inside a card run scripts and touch my data', rel: ['security-and-access', 'errors', 'architecture', 'README'] },
  { id: 'A11', set: 'new', q: 'if a call to the decision service fails does it try again', rel: ['sdk-and-webmcp', 'reflex-internals', 'errors', 'symbi-reflex'] },
  { id: 'A12', set: 'new', q: "what happens to a page's past versions when you delete it", rel: ['safe-collaboration', 'document-operations'] },
  { id: 'A13', set: 'new', q: 'why does an old link to a removed feature give not found', rel: ['history'] },
  { id: 'A14', set: 'new', q: 'who is allowed to wipe all the automatic organizing and start over', rel: ['reflex-internals', 'security-and-access'] },
  { id: 'A15', set: 'new', q: 'how is the helper in the side panel different from the background organizer', rel: ['assistant-and-research', 'README', 'system-map', 'operations'] },
  { id: 'A16', set: 'new', q: 'where are the passwords for outside services kept', rel: ['security-and-access', 'data-model', 'architecture', 'chat-internals', 'mcp-and-api'] },
  { id: 'A17', set: 'new', q: 'how often does the board update by itself', rel: ['canvas-ui', 'architecture'] },
  { id: 'A18', set: 'new', q: 'can two agents work on separate copies of the same page at once', rel: ['safe-collaboration', 'mcp-and-api', 'architecture'] },
  { id: 'A19', set: 'new', q: 'what does the little robot do for people who get dizzy from animation', rel: ['brand-and-ui', 'assistant-and-research'] },
  { id: 'A20', set: 'new', q: 'how big can a reply from the decision service be', rel: ['sdk-and-webmcp', 'errors', 'reflex-internals'] },
  { id: 'A21', set: 'new', q: 'wat happens wen my token gets taken away while a job waits', rel: ['reflex-internals', 'security-and-access', 'errors', 'mcp-and-api'] },
  { id: 'A22', set: 'new', q: 'keybord shortcut to look for stuff on the board', rel: ['canvas-ui'] },
  { id: 'A23', set: 'new', q: 'how do i hook up claude desktop', rel: ['mcp-and-api'] },
  { id: 'U1', set: 'new', q: 'how do i invite a teammate by email', rel: [] },
  { id: 'U2', set: 'new', q: 'is there a windows installer', rel: [] },
  { id: 'U3', set: 'new', q: 'can i switch the interface language to spanish', rel: [] },
  { id: 'U4', set: 'new', q: 'does it post updates to slack', rel: [] },
  { id: 'U5', set: 'new', q: 'how do i turn on two-factor login', rel: [] },
  { id: 'U6', set: 'new', q: 'how do i download my whole workspace as a zip', rel: [] },
  { id: 'A24', set: 'new', q: 'what is the biggest file i can upload', rel: ['errors'] },
  { id: 'U8', set: 'new', q: 'can it send a webhook when a page changes', rel: [] },
  { id: 'U9', set: 'new', q: 'is there an ipad app', rel: [] },
];
