// Ground truth = atlas files that contain the answer (verified with grep). [] = no answer exists.
// Rewrites and sample answers were written with generic vocabulary only (no product terms such as
// "pins", "Reflex", "Jev", "canvas", "70%"), to mimic an LLM that has never seen this corpus.
export const queries = [
  // easy (first test round)
  { id: 'E1', set: 'easy', q: 'reciprocal rank fusion bm25 ranking', rel: ['search-and-brain-tools'] },
  { id: 'E2', set: 'easy', q: "How do I keep someone else from overwriting my edits while I'm working on a document?", rel: ['safe-collaboration', 'system-map', 'README', 'errors'] },
  { id: 'E3', set: 'easy', q: 'Where does the app keep its files on disk?', rel: ['data-model', 'architecture', 'system-map'] },
  { id: 'E4', set: 'easy', q: 'How do I run the automated tests?', rel: ['operations', 'testing'] },
  { id: 'E5', set: 'easy', q: 'How do I change the colors for dark mode?', rel: ['brand-and-ui'] },
  { id: 'E6', set: 'easy', q: 'What happens to search if the local embedding model is missing?', rel: ['search-and-brain-tools', 'errors', 'plan-status', 'operations'] },
  { id: 'E7', set: 'easy', q: 'Can an AI agent approve its own organization proposal?', rel: ['security-and-access', 'errors', 'reflex-internals', 'safe-collaboration', 'symbi-reflex'] },
  { id: 'E8', set: 'easy', q: 'Which status code do I get when the Reflex job queue is full?', rel: ['errors', 'reflex-internals'] },
  { id: 'E9', set: 'easy', q: 'What is the office parking policy?', rel: [] },
  { id: 'E10', set: 'easy', q: 'How do I deploy SymbiKnow to Kubernetes?', rel: [] },
  { id: 'E11', set: 'easy', q: 'How many vacation days do employees get?', rel: [] },
  // hard (vocabulary mismatch)
  { id: 'H1', set: 'hard', q: 'If my laptop loses power right while saving, could I end up with a half-written file?', rel: ['data-model', 'architecture'],
    rw: 'crash during save partial file corruption power loss safe write durability',
    hyde: 'Saves are crash-safe. Each file is first written to a temporary file, flushed to disk, and then renamed over the original, so a power cut during a save leaves either the old version or the new version, never a half-written file.' },
  { id: 'H2', set: 'hard', q: 'Can a bot rubber-stamp its own homework?', rel: ['security-and-access', 'errors', 'reflex-internals', 'safe-collaboration', 'symbi-reflex'],
    rw: 'can an AI agent approve its own changes self-approval review permission',
    hyde: 'No. An AI agent cannot approve its own proposed changes. Changes suggested by an agent must be reviewed and approved by a human user with permission.' },
  { id: 'H3', set: 'hard', q: 'What stops the tidy-up robot from messing with things I corrected myself?', rel: ['reflex-internals', 'symbi-reflex', 'data-model'],
    rw: 'prevent automatic organizer from overwriting manual user edits corrections protected fields',
    hyde: 'When you edit a field by hand, it is marked as manually set and locked, so the automatic organizer will no longer change that field. Your manual corrections always win over automatic changes.' },
  { id: 'H4', set: 'hard', q: 'How certain must the organizer feel before it goes ahead without asking anyone?', rel: ['reflex-internals', 'symbi-reflex'],
    rw: 'confidence threshold automatic organizer apply changes without human approval',
    hyde: 'Automatic changes are only applied when the model confidence is above a configurable threshold, for example 80%. Below the threshold the change is held for human review.' },
  { id: 'H5', set: 'hard', q: 'Will looking things up keep working on a plane with no wifi?', rel: ['search-and-brain-tools', 'errors', 'operations', 'plan-status'],
    rw: 'does search work offline without internet connection local',
    hyde: 'Yes. Search runs entirely on your machine. The search index and the model it uses are stored locally, so searching keeps working without an internet connection.' },
  { id: 'H6', set: 'hard', q: 'Who gets the credit in the history when an assistant rewrites a page?', rel: ['system-map', 'README', 'safe-collaboration', 'document-operations'],
    rw: 'version history author attribution when AI assistant edits a document',
    hyde: "Every edit is saved in the document's version history with the name of whoever made it. When an AI assistant edits a page, the change is recorded under the assistant's name." },
  { id: 'H7', set: 'hard', q: 'How do I make the screen easier on my eyes at night?', rel: ['brand-and-ui'],
    rw: 'dark mode theme switch night',
    hyde: "Turn on dark mode. Use the theme toggle to switch between light and dark themes; the app can also follow your system's dark mode setting." },
  { id: 'H8', set: 'hard', q: 'Which old pieces got thrown away in the big cleanup?', rel: ['history', 'symbi-reflex', 'data-model'],
    rw: 'features removed deleted in refactor cleanup deprecated modules',
    hyde: 'The refactor removed several old features and modules. The deleted code included legacy actions and services that are no longer used; their old data files remain readable but are no longer written.' },
  { id: 'H9', set: 'hard', q: 'If I only let a helper see one board, can it still peek at notes on other boards when it looks things up?', rel: ['search-and-brain-tools', 'security-and-access', 'mcp-and-api'],
    rw: 'scoped access token limited to one board can search results include other boards permissions',
    hyde: "No. When an agent's access is limited to one board, search results are filtered to that board only. Documents on other boards are excluded from search, so the agent cannot see them." },
  { id: 'H10', set: 'hard', q: "Why might a 'next page' of results suddenly stop working right after a teammate saves something?", rel: ['search-and-brain-tools'],
    rw: 'search pagination cursor invalid stale after index update document saved',
    hyde: 'Search result pages use a cursor tied to a snapshot of the index. When someone saves a document, the index changes and old cursors become invalid, so requesting the next page fails and you need to run the search again.' },
  { id: 'H11', set: 'hard', q: 'The background helper keeps refusing new work. How many jobs can pile up before that happens?', rel: ['reflex-internals', 'errors'],
    rw: 'background job queue full maximum pending jobs limit rejected',
    hyde: "The background job queue has a maximum number of pending jobs. When the limit is reached, new jobs are rejected with a 'queue is full' error until existing jobs finish." },
  { id: 'N1', set: 'hard', q: 'How much does a team plan cost per month?', rel: [],
    rw: 'pricing team plan monthly subscription cost', hyde: 'The Team plan costs a fixed price per user per month, billed monthly or annually.' },
  { id: 'N2', set: 'hard', q: 'Can people sign in with their Google or Microsoft work account?', rel: [],
    rw: 'single sign-on SSO Google Microsoft OAuth login', hyde: 'Yes, users can sign in with single sign-on using Google Workspace or Microsoft Entra ID accounts through OAuth.' },
  { id: 'N3', set: 'hard', q: 'How do I save a board as a PDF to send to a client?', rel: [],
    rw: 'export board to PDF download print', hyde: 'To export a board as a PDF, open the menu and choose Export, then PDF. The whole board is rendered into a PDF file you can download and share.' },
  { id: 'N4', set: 'hard', q: 'Where can I download the iPhone or Android app?', rel: [],
    rw: 'mobile app iOS Android download App Store Google Play', hyde: 'The mobile app is available for iPhone on the App Store and for Android on Google Play.' },
];
