// Frozen invented cases from domains outside Project Atlas. No customer or workspace data.
export type HeldoutDocument = { title: string; body: string };
export type HeldoutDuplicate = { name: string; source: HeldoutDocument; target: HeldoutDocument; truth: 'copy' | 'older_version' | 'distinct' };
export type HeldoutLink = { name: string; source: HeldoutDocument; target: HeldoutDocument; truth: boolean };
const doc = (title: string, body: string): HeldoutDocument => ({ title, body: `# ${title}\n\n${body}` });
const bakery = doc('Bakery opening', '## Stock\nCount sourdough loaves and record the number on the counter sheet.\n\n## Setup\nPlace clean tongs beside the bread trays before opening the shop.');
const garden = doc('Greenhouse watering', '## Morning\nCheck soil moisture in the tomato beds every morning. Water only beds with dry soil.\n\n## Record\nWrite the watering date and bed number on the greenhouse board.');
const library = doc('Book return desk', '## Check\nScan the returned book barcode and check for damaged pages.\n\n## Shelf\nPut undamaged books on the shelving cart in call-number order.');
const bicycle = doc('Bicycle tyre inspection', '## Pressure\nRead the sidewall pressure range before inflating each tyre.\n\n## Wear\nInspect the tread and replace tyres with visible fabric or deep cuts.');
const bases = [bakery, garden, library, bicycle];
const renamed = ['Morning bread counter', 'Tomato bed care', 'Returned books workflow', 'Cycle wheel safety'];
export const heldoutDuplicates: HeldoutDuplicate[] = [
  ...bases.map((source, index) => ({ name: `copy-${index}`, source, target: { title: renamed[index], body: source.body.replace(/^# .+/, `# ${renamed[index]}`) }, truth: 'copy' as const })),
  ...bases.map((source, index) => ({ name: `older-${index}`, source, target: doc(source.title + ' updated', source.body.replace(/^# .+\n\n/, '') + '\n\n## Closing check\nThe closing supervisor signs the completed checklist and stores it in the blue office folder.'), truth: 'older_version' as const })),
  { name: 'different-bakery-stock', source: bakery, target: doc('Bakery supplier ordering', '## Orders\nEmail the flour supplier each Thursday with the next week\'s flour requirement.\n\n## Invoice\nMatch the delivery invoice to the flour order before paying the supplier.'), truth: 'distinct' },
  { name: 'different-greenhouse-maintenance', source: garden, target: doc('Greenhouse roof maintenance', '## Glass\nCheck the roof panes for cracks once per quarter.\n\n## Repairs\nClose the affected aisle while the contractor replaces broken glass.'), truth: 'distinct' },
  { name: 'different-library-events', source: library, target: doc('Library author evening', '## Speakers\nInvite local authors to read at the Friday evening event.\n\n## Seating\nArrange thirty chairs and reserve the front row for accessibility needs.'), truth: 'distinct' },
  { name: 'different-bicycle-routes', source: bicycle, target: doc('Bicycle route planning', '## Route\nChoose quiet roads and avoid the steep hill beside the station.\n\n## Meetup\nMeet riders at the park gate at nine on Sunday morning.'), truth: 'distinct' },
];
export const heldoutLinks: HeldoutLink[] = [
  { name: 'deposit-before-booking', source: doc('Room booking', 'Confirm a room booking only after calculating and collecting the deposit described in the deposit policy.'), target: doc('Deposit policy', 'Room reservations require a deposit equal to one fifth of the total hire price. Collect the deposit before confirming the booking.'), truth: true },
  { name: 'event-runbook-implements-plan', source: doc('Food festival runbook', 'Open the north gate at noon. Place the vegetarian stalls along the east aisle and close ticket sales at six.'), target: doc('Food festival plan', 'The festival must admit visitors through the north gate from noon. Vegetarian stalls belong in the east aisle. Ticket sales finish at six.'), truth: true },
  { name: 'garden-example-crop-rotation', source: doc('Plot seven rotation', 'Plot seven grew beans last season. Plant cabbages there this season, then grow roots next year to avoid repeating the same crop family.'), target: doc('Crop rotation', 'Crop rotation changes the crop family grown in a plot each season. A sequence of legumes, brassicas, and roots is one example.'), truth: true },
  { name: 'loan-example-amortisation', source: doc('Monthly loan example', 'A borrower pays a fixed amount each month. The first payments mostly cover interest, while later payments reduce more principal.'), target: doc('Loan amortisation', 'Amortisation divides scheduled loan payments between interest and principal. With fixed monthly payments, the interest share falls as the outstanding principal falls.'), truth: true },
  { name: 'delivery-temperature-context', source: doc('Milk delivery intake', 'Read and record the milk temperature before accepting a refrigerated delivery. Reject a delivery above the safe temperature range.'), target: doc('Milk cold chain', 'Refrigerated milk must remain between one and four degrees Celsius during transport and storage. Warmer milk increases spoilage risk.'), truth: true },
  { name: 'student-guide-needs-marking', source: doc('Essay submission guide', 'Upload the essay by Friday and check the marking rubric before submitting. The rubric determines how argument, evidence, and clarity are assessed.'), target: doc('Essay marking rubric', 'Award forty percent for argument, forty percent for evidence, and twenty percent for clear writing. Unsupported claims lose evidence marks.'), truth: true },
  { name: 'garden-vs-library', source: garden, target: library, truth: false },
  { name: 'bakery-vs-bicycle', source: bakery, target: bicycle, truth: false },
  { name: 'shared-bank-word', source: doc('River bank survey', 'Measure erosion along the river bank after each flood. Photograph exposed tree roots beside the water.'), target: doc('Bank account opening', 'Bring proof of identity and address to open a savings account. The bank checks the documents before issuing an account number.'), truth: false },
  { name: 'shared-ticket-word', source: doc('Concert ticket desk', 'Scan admission tickets at the concert hall entrance and direct audience members to their numbered seats.'), target: doc('Printer support ticket', 'Open a support ticket when the office printer jams. Record the printer model and attach a photograph of the paper path.'), truth: false },
  { name: 'shared-table-word', source: doc('Dining table maintenance', 'Apply furniture wax to the oak dining table every six months. Keep hot pans off the polished surface.'), target: doc('Multiplication table lesson', 'Teach the seven times table using groups of seven counters. Ask pupils to calculate seven multiplied by eight.'), truth: false },
  { name: 'shared-greenhouse-context', source: garden, target: doc('Greenhouse staff holiday', 'Staff request summer holiday leave through the office calendar. The manager approves dates according to team availability.'), truth: false },
];
