import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { acceptanceReflexProvider } from '../features/acceptance-reflex-provider.js';
import { CanvasStore } from './storage.js';
import { jevChatTools } from './jev-chat-tools.js';
import { getJevRuntime } from './jev/runtime.js';
import { JevWorkspaceFiles } from './jev/workspace.js';

let root: string;
let activeRuntime: ReturnType<typeof getJevRuntime> | undefined;
afterEach(async () => { if (activeRuntime) { await activeRuntime.shutdown(); activeRuntime = undefined; } if (root) await rm(root, { recursive: true, force: true }); });
it('uses the shared automatic runtime for every Symbi read/request tool without allowing an agent to approve protected metadata', async () => {
  root = await mkdtemp(path.join(tmpdir(), 'reflex-symbi-tools-')); const store = new CanvasStore(root); await store.init();
  await store.deleteWorkspace('acme-team');
  const workspace = await store.createWorkspace({ name: 'Chat organizer tools' }); const canvas = await store.createCanvas(workspace.id, { name: 'Sources' });
  const block = await store.createBlock(canvas.id, { title: 'Release', content: '# Release\nA checked rollout releases the service.' });
  await store.updateSettings({ secrets: { TYPESAFE_API_KEY: 'scoped-tool-key' } });
  const runtime = activeRuntime = getJevRuntime(store, { fetcher: acceptanceReflexProvider });
  const owner = { id: 'owner', kind: 'user' as const, access: 'write' as const, canApprove: true, canConfigure: true };
  expect((await runtime.read(workspace.id, owner)).settings.modes.label).toBe('auto');
  await runtime.idle();
  await store.updateBlock(canvas.id, block.id, { tags: [] }, 'Human');
  await runtime.idle();
  const tools = jevChatTools(store, canvas.id);
  const files = new JevWorkspaceFiles(root); const saved = await files.read(workspace.id);
  saved.vocabulary.push({ id: 'scoped-release-label', kind: 'label', name: 'Rollout', definition: 'Rollout instructions', aliases: [], state: 'active', version: 1, members: [] });
  await files.write(workspace.id, saved);
  const invoke = async (name: string, input: Record<string, unknown>) => JSON.parse(String(await tools.find(tool => tool.name === name)!.invoke(input)));
  const requested = await invoke('jev_do', { action: 'label', blockIds: [block.id] }); expect(requested.request.canvasId).toBe(canvas.id);
  await runtime.idle();
  expect(await invoke('brain_inbox', {})).toEqual(expect.arrayContaining([expect.objectContaining({ action: 'label', state: 'pending', automaticHoldReason: 'An agent cannot approve its own proposal' })]));
  expect(await invoke('jev_profile', { blockId: block.id, query: 'release' })).toHaveProperty(`${canvas.id}:${block.id}`);
  expect(await invoke('jev_profile', {})).toHaveProperty('_coverage');
  expect(await invoke('jev_profile', { query: 'release' })).toHaveProperty('_coverage');
  expect(await invoke('find_by', { query: 'not-present' })).toEqual({});
  expect(await invoke('find_by', {})).toEqual({});
  expect(await invoke('related', { blockId: block.id })).toEqual([]);
  expect(await invoke('related', {})).toEqual([]);
  expect(await invoke('memory_map', {})).toEqual(expect.arrayContaining([expect.objectContaining({ id: 'scoped-release-label' })]));
  expect((await invoke('jev_activity', {})).jobs.length).toBeGreaterThan(0);
  expect(tools.map(tool => tool.name)).not.toContain('recall');
  await expect(invoke('jev_do', { action: 'recall', query: 'Where is the release source?' })).rejects.toThrow();
  await runtime.idle(); expect((await store.getCanvasBlock(canvas.id, block.id)).tags).toEqual([]);
  expect(tools.map(tool => tool.name)).not.toContain('jev_resolve');
  expect(tools.map(tool => tool.name)).not.toContain('where_to_put');
});
