# Generated by code-discipline gherkin_yaml; source: app-safety.feature.yaml
Feature: Reviewed app safety

  Scenario: Removed canvas controls and floating navigation stay absent
    Given a fresh workspace
    When I open the current canvas in a browser
    Then removed canvas controls and floating navigation are absent

  Scenario: Compact navigation can create workspaces and canvases
    Given a fresh workspace
    When I open the current canvas in a browser
    And I use the compact navigation to create a workspace and canvas
    Then the compact navigation creations survive reload

  Scenario: Moving a document preserves cross-canvas references
    Given a fresh workspace
    When I move a document referenced by a third canvas
    Then reloading all affected canvases preserves the moved reference

  Scenario: Reviewed creation Undo preserves later edits and cross-canvas citations
    Given a fresh workspace
    When I open the current canvas in a browser
    And I review a new document before a later human edit and citation
    Then reviewed deletion refuses the later edit and saved citation
    When I deliberately remove the citation and review the current document
    Then the reviewed deletion survives reload and retains document history

  Scenario: Reviewed edit Undo preserves simultaneous human metadata
    Given a fresh workspace
    When I open the current canvas in a browser
    And a human updates metadata after I review an agent document edit
    Then restoring the old reviewed edit refuses to overwrite the human metadata
    When I review the current document before restoring its source
    Then the restored source and human metadata survive reload

  Scenario: Damaged research entries preserve valid answers and manual notes
    Given a fresh workspace
    When I open the current canvas in a browser
    And I reopen research with valid answers and damaged saved entries
    Then the recovered research retains its answer and manual note
    When I save the recovered research as files
    Then recovered answers and their citations survive reload

  Scenario: Saved document selection survives navigation and a file refresh
    Given a fresh workspace
    When I prepare two saved documents for view history
    And I open the current canvas in a browser
    And I select the first document after viewing another document
    Then the selected document remains selected after saving its checkbox
    When I close the saved document inspector
    Then the saved checkbox survives browser reload and reselection

  Scenario: Zoom controls keep documents and revision history unchanged
    Given a fresh workspace
    When I open the current canvas in a browser
    And I return the camera through the zoom controls before its deferred end report
    Then reloading after camera changes preserves documents and revision history
