# Generated by code-discipline gherkin_yaml; source: assistant-avatar.feature.yaml
@avatar-preview
Feature: Shared assistant artwork and motion preview

  Scenario: Every pose works for both assistants and both themes
    Given the real assistant artwork preview
    When I observe resting avatars at their default app size
    Then both companions keep calmly moving while at rest
    And the conversation has one larger avatar in its header
    When I preview every pose for Symbi and Symbi Reflex in both themes
    Then every pose has loaded artwork and a meaningful accessible name
    And changing Symbi Reflex's activity preserves Symbi's activity
    When I choose the app sizes and reduce motion
    Then both portraits use the chosen size and all avatar motion stops

  Scenario: System reduced motion and conversation examples remain usable
    Given the real assistant artwork preview
    When the browser requests reduced motion
    Then both assistants remain visible without animations
    When I try the conversation mapping example
    Then the example shows its map and completion while Symbi Reflex stays at rest

  Scenario: Interrupted or failed activity never celebrates completion
    Given the real assistant artwork preview
    When I interrupt each assistant with pause cancellation error and disconnection
    Then interrupted companions keep calm idle life without showing done
