# Generated by code-discipline gherkin_yaml; source: canvas-discovery.feature.yaml
Feature: Discovering and organizing a large canvas

  Scenario: Nested groups and tags survive reload and appear in search
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "API plan" containing "Endpoint choices"
    And I assign the new document to nested group "custom:research/benchmarks" with tag "api"
    Then reloading the canvas keeps the nested group and tag
    And searching for "API plan" reports its canvas, group, and title match

  Scenario: Search remains on the canvas and reveals a match in one action
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "API plan" containing "Endpoint choices"
    And I open the current canvas in a browser
    And I search the canvas for "API plan"
    Then I see a match counter while the canvas stays visible
    When I show the "API plan" search result on the canvas
    Then the "API plan" card is highlighted and search stays open

  Scenario: Group connections appear on a movable canvas with real document previews
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "Real note" containing "This note has real details"
    And I assign the new document to nested group "custom:research/notes" with tag "example"
    And I add a Markdown block called "Other note" containing "A related document"
    And I assign the new document to nested group "custom:planning/notes" with tag "example"
    And I connect "Real note" to "Other note"
    And I open the current canvas in a browser
    And I zoom out to the group overview
    Then I can see the group connection on the canvas and move the view
    When I browse the group list
    Then the group preview shows the "Real note" title
    When I open the Research group
    Then the Notes subgroup appears on the canvas
    When I open the Notes subgroup
    Then the canvas shows the real document preview

  Scenario: Large canvases open through supergroups, groups, subgroups, and files
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I fill it with linked groups and nested research documents
    And I open the current canvas in a browser
    And I zoom out to the group overview
    Then I see supergroups connected on the canvas
    When I zoom in over the Research supergroup
    Then I see its Research group on the canvas
    When I zoom in over the Research group
    Then I see connected Notes and Benchmarks subgroups
    When I zoom in over the Notes subgroup
    Then the canvas shows the research document card
    When I zoom out to the subgroup map
    Then I see connected Notes and Benchmarks subgroups

  Scenario: Connection focus and layout preview leave saved positions alone until applied
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "Source" containing "The source"
    And I add a Markdown block called "Target" containing "The target"
    And I connect "Source" to "Target"
    And I open the current canvas in a browser
    And I select the "Source" card
    Then I see connection focus and its linked document
    When I preview and cancel arrange by connections
    Then reloading the canvas keeps the original positions

  Scenario: Suggested tag groups can be accepted and undone
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "API plan" containing "Endpoint choices"
    And I assign the new document to nested group "custom:research/benchmarks" with tag "api"
    And I open the current canvas in a browser
    And I preview and accept tag grouping
    Then reloading the canvas puts "API plan" in a tag group
    When I undo the suggested grouping
    Then reloading the canvas keeps the nested group and tag

  Scenario: Bookmarks and canvas history let me return to a named place
    Given a fresh workspace
    When I create a second canvas called "Second canvas"
    And I open the current canvas in a browser
    And I save a bookmark called "Starting point"
    And I navigate to "Second canvas" and back
    Then the "Starting point" bookmark remains after reloading

  Scenario: Follow-up answers extend one live evidence canvas
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "Launch evidence" containing "The mobile release has two failing tests"
    And I configure chat for the conversation canvas
    And I open the current canvas in a browser
    And I ask "What blocks the launch?" with selected evidence
    Then the conversation canvas has 1 answers and one reusable source
    When I visit another canvas and continue the conversation
    And I ask "Map which tests failed and how they block the launch" with selected evidence
    And I can reopen the accumulated conversation canvas
    Then the conversation canvas has 2 answers and one reusable source
    And the research canvas shows its answer structure with secondary controls tucked away
    When I switch to dark mode
    Then the research canvas uses dark surfaces and retains every block
    When I ask a direct factual question in chat
    Then the direct answer stays in chat and adds no research block
    And the assistant shows its current scope and a way to turn the answer into a map

  Scenario: A connection failure keeps the chat draft and offers recovery
    Given a fresh workspace
    When I open the current canvas in a browser
    And I keep a chat draft while the canvas API becomes unreachable
    Then I can reconnect without losing the chat draft

  Scenario: Temporary research uses the normal canvas actions
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "Launch evidence" containing "The mobile release has two failing tests"
    And I configure chat for the conversation canvas
    And I open the current canvas in a browser
    And I ask "What blocks the launch?" with selected evidence
    Then the conversation canvas has 1 answers and one reusable source
    And I can add, read, search, undo, and save with the normal canvas controls

  Scenario: Agent research blocks use every canvas document loader
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "Launch evidence" containing "The mobile release has two failing tests"
    And I configure chat for the conversation canvas
    And I open the current canvas in a browser
    And I ask for rich research blocks
    Then I can view and save the rich blocks with their original formats
