# Generated by code-discipline gherkin_yaml; source: canvas.feature.yaml
Feature: Markdown canvas

  Scenario: SymbiKnow explains the shared infinite canvas and remembers dark mode
    Given a fresh workspace
    When I open SymbiKnow in a browser
    Then the app identifies an infinite canvas for people and AI
    When I switch to dark mode
    Then the dark canvas remains selected after reloading
    When I switch to light mode
    Then the light canvas is selected

  Scenario: A document remains available after reloading the canvas
    Given a fresh workspace
    When I add a Markdown block called "Launch Notes" containing "Ship the beta"
    Then the canvas contains the "Launch Notes" block
    And the block is backed by a Markdown file containing "Ship the beta"
    And searching for "Ship the beta" finds the block

  Scenario: An unchanged canvas skips its body and an external edit refreshes it
    Given a fresh workspace
    When I add a Markdown block called "Refresh check" containing "Before"
    And I load the canvas and remember its revision
    Then loading the unchanged canvas sends no body
    When I edit the Markdown file outside the app from "Before" to "After"
    Then loading with the old revision returns the updated document

  Scenario: New manual and assistant cards do not cover existing cards
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "First note" containing "# First"
    And I add a Markdown block called "Second note" containing "# Second"
    And I create a Markdown block called "Assistant note" at x 100 and y 100
    Then reloading the canvas shows three cards without overlap

  Scenario: Creating and finding a document reveals its card
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I open the current canvas in a browser
    And I save a new block titled "First note"
    And I save a new block titled "Second note"
    Then the new card is highlighted and the cards do not overlap
    When I search for "First note" and choose Show on canvas
    Then the searched card is highlighted without opening its editor

  Scenario: The OpenRouter key is saved without being returned to the browser
    Given a fresh workspace
    When I configure the OpenRouter model "openai/gpt-4o-mini" and an API key
    Then the settings report that an API key is saved
    And the settings response does not reveal the API key

  Scenario: Chat explains missing configuration
    Given a fresh workspace
    When I send a chat message without an API key
    Then the chat request is rejected with a settings error

  Scenario: Streaming chat explains missing configuration
    Given a fresh workspace
    When I send a streaming chat message without an API key
    Then the chat request is rejected with a settings error

  Scenario: A deleted document stays deleted after reloading the canvas
    Given a fresh workspace
    When I add a Markdown block called "Temporary Note" containing "Remove this note"
    And I delete the new document
    Then reloading the canvas does not restore the deleted document
    And the deleted Markdown file is gone

  Scenario: Deleting a canvas from the sidebar removes its documents and returns to a surviving canvas
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I add a Markdown block called "Scratch note" containing "Disposable research"
    And I open the current canvas in a browser
    And I delete the current canvas in the browser
    Then the deleted canvas is gone after reloading

  Scenario: A suggested canvas layout stays after reloading
    Given a fresh workspace
    When I arrange the "Roadmap overview" block at x -360 and y 640
    Then reloading the canvas keeps "Roadmap overview" at x -360 and y 640

  Scenario: Purpose and reviewer labels stay with the block
    Given a fresh workspace
    When I label "Roadmap overview" as "guide" for "Engineering"
    Then reloading the canvas shows "Roadmap overview" as "guide" for "Engineering"

  Scenario: An accepted connection becomes a saved canvas edge
    Given a fresh workspace
    When I connect "Roadmap overview" to "Launch checklist"
    Then reloading the canvas keeps that connection

  Scenario: New chat clears the conversation without changing the canvas
    Given a fresh workspace
    When I configure the OpenRouter model "openai/gpt-4o-mini" and an API key
    And I send a chat message then press New chat
    Then the next chat request contains only the new message

  Scenario: The chat panel can be resized and remembers its width
    Given a fresh workspace
    When I drag the chat divider wider
    Then the chat panel keeps its new width after reloading

  Scenario: An uploaded HTML page is previewed in Markdown and can be edited as a downloaded file
    Given a fresh workspace
    When I upload an HTML page
    Then the canvas shows its HTML preview inside a Markdown block
    And I can read the whole page and return to the canvas
    And I can switch between source and a live HTML preview in the editor
    And I can download its Markdown file and upload an edited version

  Scenario: Full-access Symbi deletes an explicitly requested document through MCP
    Given a fresh workspace
    When the assistant asks to delete "Temporary Note" and I reply "yes"
    Then "Temporary Note" is deleted through the canonical MCP tool
