# Generated by code-discipline gherkin_yaml; source: canvas-loading.feature.yaml
Feature: Fresh loading of a large canvas

  Scenario: A large canvas opens its overview before reading visible files and preserves fresh edits
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I seed 600 grouped documents for a cold canvas load
    And I open the large canvas while recording real document requests
    Then the initial overview contains fresh metadata and reads no document bodies
    When I open Reflex on the large canvas
    Then all six confidence controls appear without fetching full canvas content
    When I return to chat on the large canvas
    And I open the small release group on the large canvas
    Then only that group's visible documents are requested
    When I read and edit the selected cold document
    Then its edit survives disk readback and a browser reload
    When I change that document on disk and return from another canvas
    Then the reader shows the fresh outside edit without a cached body

  Scenario: An expanded rich canvas stays responsive without resize observer feedback
    Given a fresh workspace
    When I create an empty canvas for group automations
    And I seed 158 ungrouped responsive HTML sources
    And I open the large canvas while recording real document requests
    And I expand the rich Ungrouped canvas and resize its viewport
    Then the rich previews and Reflex controls remain usable without browser errors
    When I reload the expanded rich canvas
    Then its original source bytes and dimensions remain unchanged
