# Generated by code-discipline gherkin_yaml; source: canvas-run.feature.yaml
Feature: Canvas Jev run review

  Scenario: A canvas automation previews changes before selected apply and undo
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I preview work-area labels on the current canvas
    Then the canvas run preview leaves labels unchanged
    When I apply one selected canvas change
    Then only the selected canvas change is saved
    When I undo the selected canvas run
    Then the canvas run restores original labels

  Scenario: A canvas run skips a document edited after preview
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I preview work-area labels on the current canvas
    And I edit the selected document after its preview
    And I apply one selected canvas change
    Then the canvas run reports the stale document and keeps its label
