# Generated by code-discipline gherkin_yaml; source: chat-avatar.feature.yaml
@chat-avatar
Feature: One living companion in the chat header

  Scenario: The single enlarged avatar stays with the conversation across answers and reload
    Given a fresh workspace
    When I configure the native avatar conversation
    And I open SymbiKnow in a browser
    And I open the single companion chat
    Then the chat has one 56 pixel avatar in its header
    When I complete two native chat answers
    Then the conversation keeps one avatar and both answers
    When I reload the companion conversation and reduce motion
    Then the single companion retains its artwork and respects reduced motion
