# Generated by code-discipline gherkin_yaml; source: engine.feature.yaml
@engine
Feature: Standalone Jev engine and SDK reset

  Scenario: A caller receives typed decisions through the built SDK
    Given a real local Jev provider and the built SDK
    When I submit choice score and noul questions
    Then the provider receives exactly the caller context and questions
    And the SDK returns the validated decisions and distributions

  Scenario: Invalid provider answers fail and a subsequent call recovers
    Given a real local Jev provider and the built SDK
    When the provider returns an unoffered choice
    Then the SDK rejects the invalid decision
    When I submit choice score and noul questions
    Then the SDK returns the validated decisions and distributions

  Scenario: Transient provider failure is retried
    Given a real local Jev provider and the built SDK
    When the provider fails once with a transient status
    Then a retry returns validated decisions after two requests

  Scenario: Caller cancellation prevents network work
    Given a real local Jev provider and the built SDK
    When I cancel before submitting a decision
    Then the SDK reports cancellation with no provider request

  Scenario: Empty batches do no network work
    Given a real local Jev provider and the built SDK
    When I submit an empty question batch
    Then the SDK returns no answers with no provider request

  Scenario: Oversized state is refused locally
    Given a real local Jev provider and the built SDK
    When I submit state exceeding the decision budget
    Then the SDK rejects the state with no provider request

  Scenario: Credentials are not exposed in provider errors
    Given a real local Jev provider and the built SDK
    When the provider rejects the supplied API key
    Then the SDK returns a safe credential diagnostic
