# Generated by code-discipline gherkin_yaml; source: jev-experience.feature.yaml
Feature: Jev document experiences

  Scenario: A card requests focused analysis for one saved document
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I request Jev analysis for one document card
    Then Jev reports only that document as analyzed

  Scenario: Invalid targeted analysis is rejected before asking Jev
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I request an unsupported Jev question family
    Then the targeted Jev request is rejected

  Scenario: Intake preview recommends labels without saving a document
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I preview Jev intake for a new guide
    Then the intake preview has provenance and has saved no document

  Scenario: Accepted intake suggestions save with a new document in one write
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I preview intake with a related document and known tag
    And I save the document with its accepted intake suggestions
    Then one new document keeps its suggested labels tag and link after reloading

  Scenario: The review inbox checks changed documents in bounded batches
    Given a fresh workspace
    When I configure Jev for canvas run review
    And I open the Jev review inbox
    Then the inbox reports checked and pending documents
