# Generated by code-discipline gherkin_yaml; source: jev-removal.feature.yaml
Feature: Ordinary workflows remain available with Symbi Reflex off

  Scenario: The retired Tasks view and API remain unavailable
    Given a fresh workspace
    When I open the current canvas in a browser
    Then the retired Tasks view and API are unavailable

  Scenario: Canvas chat and settings remain available without an assistant Tasks tab
    Given a fresh workspace
    When I add a Markdown block called "Ordinary Note" containing "# Native canvas document"
    And I open the current canvas in a browser
    And I search for "Ordinary Note" and choose Show on canvas
    Then the ordinary app is visible without Jev action controls
    When I open the restored chat and settings without a Tasks tab
    Then ordinary settings remain without Jev action settings

  Scenario: Retired canvas-scoped analysis endpoints remain unavailable
    Given a fresh workspace
    When I request the removed Jev action endpoints
    Then every removed Jev action returns not found

  Scenario: A plain uploaded document saves without Jev analysis
    Given a fresh workspace
    When I open the current canvas in a browser
    And I upload a plain document without Jev suggestions
    Then the uploaded document survives reload without a Jev request
