# Generated by code-discipline gherkin_yaml; source: jev-home-retention.feature.yaml
@engine @home-retention
Feature: Preserve the current home when no destination wins

  Scenario: Leading none retains the canonical document without an evidence call
    Given an isolated home placement with "leading none" and an accepted destination gate
    When the public Jev runtime evaluates the document home
    Then one placement call and no evidence call produce a durable no change outcome
    And native reload preserves the document in its original canvas

  Scenario: A tie with none retains the canonical document without an evidence call
    Given an isolated home placement with "tied none" and an accepted destination gate
    When the public Jev runtime evaluates the document home
    Then one placement call and no evidence call produce a durable no change outcome
    And native reload preserves the document in its original canvas
