# Generated by code-discipline gherkin_yaml; source: jev-indexed-grouping.feature.yaml
@engine @indexed-grouping
Feature: Evidence-checked grouping from Jev indexes labels and links

  Scenario: Supported grouping uses a durable Jev logical index and current organization signals
    Given an isolated indexed grouping fixture with "supported" semantic evidence
    When Jev profiles the source and then evaluates its filing through the public runtime
    Then its logical topics and exact evidence survive native reload
    And the filing decision receives the current logical index labels and directional links
    And the supported group is durably applied without changing content labels or positions

  Scenario: A directional link and incidental words cannot force grouping
    Given an isolated indexed grouping fixture with "incidental linked" semantic evidence
    When Jev profiles the source and then evaluates its filing through the public runtime
    Then its logical topics and exact evidence survive native reload
    And the filing decision receives the current logical index labels and directional links
    And semantic rejection leaves the document ungrouped at the existing confidence threshold

  Scenario: Retrieval signals cannot lower the grouping confidence threshold
    Given an isolated indexed grouping fixture with "below threshold" semantic evidence
    When Jev profiles the source and then evaluates its filing through the public runtime
    Then its logical topics and exact evidence survive native reload
    And the filing decision receives the current logical index labels and directional links
    And semantic rejection leaves the document ungrouped at the existing confidence threshold
