# Generated by code-discipline gherkin_yaml; source: jev-document-operation.feature.yaml
@engine @document-operation
Feature: One durable automatic document operation

  Scenario: Six action outcomes share one durable document completion
    Given an isolated document operation with an offline decision provider
    When the automatic document operation completes
    Then six current outcomes survive reload in three workspace writes
    And the document content manual organization and position are preserved
    When unchanged automatic documents are checked again
    Then no new decisions or document operations are created

  Scenario: Removed actions cannot restart work or change a document
    Given an isolated document operation with an offline decision provider
    When the seven removed actions are requested
    Then each removed action is rejected without decisions jobs or durable writes
    And the document content manual organization and position are preserved
