# Generated by code-discipline gherkin_yaml; source: review-fixes.feature.yaml
Feature: Desktop review fixes

  Scenario: Escape closes only the topmost surface
    Given a fresh workspace
    When I open the current canvas in a browser
    And I open a saved document in the reader and then its file history
    Then Escape closes the file history and keeps the reader open
    And a second Escape returns to the canvas without changing the document

  Scenario: Entering a scattered group shows every document
    Given a fresh workspace
    When I save three documents of one group far apart on a new canvas
    And I open the current canvas in a browser
    And I open the scattered group
    Then every document in the group is visible in the canvas view
    And the saved document positions are unchanged after reload
