# Generated by code-discipline gherkin_yaml; source: symbi-reflex.feature.yaml
@automatic-reflex
Feature: Symbi Reflex runs the six retained actions automatically

  Scenario: Independent automatic action questions share provider requests and preserve source isolation across reload
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When distinct rollout sources and existing work are saved through the ordinary API
    Then all six Reflex actions finish without a request or an open panel
    And independent typed action questions share real provider requests without mixing their saved sources
    When I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    And I reload the automatic Reflex canvas
    Then automatic classification and unchanged manual tasks survive reload
    And independent typed action questions share real provider requests without mixing their saved sources

  Scenario: Saved sources are organized before the Reflex panel opens and results survive reload
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When related sources and existing rollout work are saved through the ordinary API
    Then all six Reflex actions finish without a request or an open panel
    When I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    Then the Reflex panel contains findings without action approval or mode controls
    When I reload the automatic Reflex canvas
    Then automatic classification and unchanged manual tasks survive reload

  Scenario: Source changes refresh automatic checks while manually updated tasks remain intact
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When related sources and existing rollout work are saved through the ordinary API
    Then all six Reflex actions finish without a request or an open panel
    When the saved source and existing work change through the ordinary API
    Then all six Reflex actions refresh for the current source automatically
    When I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    And I reload the automatic Reflex canvas
    Then the refreshed results survive reload without additional tasks or approvals

  Scenario: Repeated reconciliation and browser reload keep unchanged completed sources stable
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When related sources and existing rollout work are saved through the ordinary API
    Then all six Reflex actions finish without a request or an open panel
    And I record the completed automatic knowledge and its job history
    When I save the unchanged automatic settings through three reconciliation passes
    Then completed sources and their automatic results have not restarted or changed
    When I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    And I reload the automatic Reflex canvas
    And I save the unchanged automatic settings through three reconciliation passes
    Then completed sources and their automatic results have not restarted or changed

  Scenario: Each automatic action has one confidence threshold that saves and survives reload
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When related sources and existing rollout work are saved through the ordinary API
    Then all six Reflex actions finish without a request or an open panel
    When I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    Then the primary Reflex tab has exactly six single confidence controls at seventy percent
    When I change the "Organize into groups" confidence threshold to 85 percent
    And I change the "Find useful connections" confidence threshold to 65 percent
    Then only those confidence thresholds save automatically without an apply action
    When I reload the automatic Reflex canvas
    Then the individual confidence thresholds survive API readback and browser reload

  Scenario: Removed actions and command recipes are unavailable
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When every removed Reflex action and command recipe is submitted through HTTP
    Then all twenty-one removed actions return bad requests and commands return not found

  Scenario: Reset restarts every workspace document and preserves manual knowledge and confidence settings
    Given a fresh workspace
    And an isolated automatic Reflex workspace with a saved provider key
    When related sources and existing rollout work are saved through the ordinary API
    Then all six Reflex actions finish without a request or an open panel
    When manual organization is saved and automatic processing is paused with another workspace canvas
    And I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    Then Reflex reports paused processing and offers the workspace reset
    When I reset and rerun Jev from Reflex
    Then all six actions rerun for every workspace source while manual knowledge and settings remain
    When I reload the automatic Reflex canvas
    Then the reset results and confidence settings survive browser reload
    When I reset and rerun Jev from Reflex
    Then all six actions rerun for every workspace source while manual knowledge and settings remain

  Scenario: An unavailable provider is reported without pending approvals
    Given a fresh workspace
    And an isolated automatic Reflex workspace without a provider key
    When related sources and existing rollout work are saved through the ordinary API
    And I open the current canvas in a browser
    And I open Reflex only to observe automatic results
    Then Reflex reports the missing provider key without requesting action approval
    And the workspace reset is disabled without a provider and makes no request
