# Generated by code-discipline gherkin_yaml; source: symbi-search.feature.yaml
Feature: Symbi search asks Jev once to judge the candidate documents

  Scenario: Combined search shows the judged document first and reports nothing found when no document answers
    Given a fresh workspace
    And a search canvas with a saved provider key and an agent token
    When a sectioned rollback runbook and an unrelated brand guide are saved through the ordinary API
    And an agent asks Symbi "how do I restore the previous deployment" in combined mode
    Then Symbi shows the rollback runbook first with the snippets Jev judged
    And one provider request judged the candidates with a rank and a gate question
    When an agent asks Symbi "is there an ipad deployment" in combined mode
    Then Symbi reports that nothing answers the question

  Scenario: Empty requested document selection searches the permitted canvas
    Given a fresh workspace
    And a search canvas with a saved provider key and an agent token
    When a sectioned rollback runbook and an unrelated brand guide are saved through the ordinary API
    And an agent asks Symbi about restoring deployment with an empty document selection
    Then local Symbi search checks permitted documents and finds the rollback runbook without a provider request
