# Generated by code-discipline gherkin_yaml; source: tasks-canvas.feature.yaml
Feature: Tasks use the ordinary canvas board and durable task records

  Scenario: Task status columns stay visible and a drag saves status without moving documents
    Given a fresh workspace
    When I add a Markdown block called "Release evidence" containing "# Release evidence"
    And I open the current canvas in a browser
    And I open the Tasks canvas page
    Then the four task status columns are visible in order
    When I create a task called "Review release" in the Blocked column
    Then the task is durable in Blocked
    When I drag "Review release" to the Done column
    Then the task is durable in Done and document positions are unchanged
    When I reload the Tasks canvas page
    Then the task remains in Done with no browser errors

  Scenario: Saved order within a status column survives a canvas reload
    Given a fresh workspace
    When I create three ordered tasks on the current canvas
    And I open the current canvas in a browser
    And I open the Tasks canvas page
    And I drag the last task before the first task in To do
    Then the task order is saved and remains after reloading the board
